HEADER_LENGTH_IN_BYTES = 12
HEADER_PACKET_ID_LENGTH_IN_BYTES = 2
HEADER_QUESTION_COUNT_LENGTH_IN_BYTES = 2
HEADER_ANSWER_COUNT_LENGTH_IN_BYTES = 2
HEADER_AUTHORITY_COUNT_LENGTH_IN_BYTES = 2
HEADER_ADDITIONAL_COUNT_LENGTH_IN_BYTES = 2
